//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSoft.LS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSoft.LS.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 帐号编码 的本地化字符串。
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号名称 的本地化字符串。
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属组织部门或客户的名称 的本地化字符串。
        /// </summary>
        public static string AccountOrganName {
            get {
                return ResourceManager.GetString("AccountOrganName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号密码 的本地化字符串。
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属员工或客户联系人的姓名 的本地化字符串。
        /// </summary>
        public static string AccountStaffName {
            get {
                return ResourceManager.GetString("AccountStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号类别 的本地化字符串。
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实发箱数 的本地化字符串。
        /// </summary>
        public static string ActualBoxes {
            get {
                return ResourceManager.GetString("ActualBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实发件数 的本地化字符串。
        /// </summary>
        public static string ActualPieces {
            get {
                return ResourceManager.GetString("ActualPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实发垛数 的本地化字符串。
        /// </summary>
        public static string ActualPiles {
            get {
                return ResourceManager.GetString("ActualPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实发万只 的本地化字符串。
        /// </summary>
        public static string ActualTenThousands {
            get {
                return ResourceManager.GetString("ActualTenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际运费 的本地化字符串。
        /// </summary>
        public static string ActualTransportCharges {
            get {
                return ResourceManager.GetString("ActualTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际单价 的本地化字符串。
        /// </summary>
        public static string ActualTransportPrice {
            get {
                return ResourceManager.GetString("ActualTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实发吨数 的本地化字符串。
        /// </summary>
        public static string ActualTunnages {
            get {
                return ResourceManager.GetString("ActualTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 街道门牌号码 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议单价 的本地化字符串。
        /// </summary>
        public static string AgreementTransportPrice {
            get {
                return ResourceManager.GetString("AgreementTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 划拨出库力支费 的本地化字符串。
        /// </summary>
        public static string AllocateOutWarehouseForceFee {
            get {
                return ResourceManager.GetString("AllocateOutWarehouseForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许审批 的本地化字符串。
        /// </summary>
        public static string AllowApprove {
            get {
                return ResourceManager.GetString("AllowApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许注销/取消 的本地化字符串。
        /// </summary>
        public static string AllowCancel {
            get {
                return ResourceManager.GetString("AllowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许删除 的本地化字符串。
        /// </summary>
        public static string AllowDelete {
            get {
                return ResourceManager.GetString("AllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许查看详细 的本地化字符串。
        /// </summary>
        public static string AllowDetail {
            get {
                return ResourceManager.GetString("AllowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许调度 的本地化字符串。
        /// </summary>
        public static string AllowDispatch {
            get {
                return ResourceManager.GetString("AllowDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许导出 的本地化字符串。
        /// </summary>
        public static string AllowExport {
            get {
                return ResourceManager.GetString("AllowExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许导入 的本地化字符串。
        /// </summary>
        public static string AllowImport {
            get {
                return ResourceManager.GetString("AllowImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许修改 的本地化字符串。
        /// </summary>
        public static string AllowModify {
            get {
                return ResourceManager.GetString("AllowModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许新增 的本地化字符串。
        /// </summary>
        public static string AllowNew {
            get {
                return ResourceManager.GetString("AllowNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许打开 的本地化字符串。
        /// </summary>
        public static string AllowOpen {
            get {
                return ResourceManager.GetString("AllowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许打印 的本地化字符串。
        /// </summary>
        public static string AllowPrint {
            get {
                return ResourceManager.GetString("AllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许查询 的本地化字符串。
        /// </summary>
        public static string AllowSearch {
            get {
                return ResourceManager.GetString("AllowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄库计划未发完是否结算 的本地化字符串。
        /// </summary>
        public static string AllowStatementWhenConsignedDeliverPlanNotCompleted {
            get {
                return ResourceManager.GetString("AllowStatementWhenConsignedDeliverPlanNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许提交 的本地化字符串。
        /// </summary>
        public static string AllowSubmit {
            get {
                return ResourceManager.GetString("AllowSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批意见 的本地化字符串。
        /// </summary>
        public static string ApproveComment {
            get {
                return ResourceManager.GetString("ApproveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批运费 的本地化字符串。
        /// </summary>
        public static string ApprovedTransportCharges {
            get {
                return ResourceManager.GetString("ApprovedTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批单价 的本地化字符串。
        /// </summary>
        public static string ApprovedTransportPrice {
            get {
                return ResourceManager.GetString("ApprovedTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批结论 的本地化字符串。
        /// </summary>
        public static string ApproveResult {
            get {
                return ResourceManager.GetString("ApproveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批人 的本地化字符串。
        /// </summary>
        public static string ApproverName {
            get {
                return ResourceManager.GetString("ApproverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批状态 的本地化字符串。
        /// </summary>
        public static string ApproveState {
            get {
                return ResourceManager.GetString("ApproveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批时间 的本地化字符串。
        /// </summary>
        public static string ApproveTime {
            get {
                return ResourceManager.GetString("ApproveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货到日期 的本地化字符串。
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到货时间 的本地化字符串。
        /// </summary>
        public static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核人 的本地化字符串。
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结存 的本地化字符串。
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结存件数 的本地化字符串。
        /// </summary>
        public static string BalancePieces {
            get {
                return ResourceManager.GetString("BalancePieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结存垛数 的本地化字符串。
        /// </summary>
        public static string BalancePiles {
            get {
                return ResourceManager.GetString("BalancePiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结存万只 的本地化字符串。
        /// </summary>
        public static string BalanceTenThousands {
            get {
                return ResourceManager.GetString("BalanceTenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结存吨数 的本地化字符串。
        /// </summary>
        public static string BalanceTunnages {
            get {
                return ResourceManager.GetString("BalanceTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期初结存 的本地化字符串。
        /// </summary>
        public static string BeginningBalance {
            get {
                return ResourceManager.GetString("BeginningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单人 的本地化字符串。
        /// </summary>
        public static string BillMaker {
            get {
                return ResourceManager.GetString("BillMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上司姓名 的本地化字符串。
        /// </summary>
        public static string BossName {
            get {
                return ResourceManager.GetString("BossName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱数 的本地化字符串。
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌 的本地化字符串。
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经营性质 的本地化字符串。
        /// </summary>
        public static string BusinessType {
            get {
                return ResourceManager.GetString("BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号码 的本地化字符串。
        /// </summary>
        public static string CarLicenseNo {
            get {
                return ResourceManager.GetString("CarLicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车号 的本地化字符串。
        /// </summary>
        public static string CarNo {
            get {
                return ResourceManager.GetString("CarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼车费 的本地化字符串。
        /// </summary>
        public static string CarpoolFee {
            get {
                return ResourceManager.GetString("CarpoolFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运单位编码 的本地化字符串。
        /// </summary>
        public static string CarrierId {
            get {
                return ResourceManager.GetString("CarrierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运单位名称 的本地化字符串。
        /// </summary>
        public static string CarrierName {
            get {
                return ResourceManager.GetString("CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运运费 的本地化字符串。
        /// </summary>
        public static string CarrierTransportCharges {
            get {
                return ResourceManager.GetString("CarrierTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算记录编码 的本地化字符串。
        /// </summary>
        public static string CarrierTransportChargesSettlementId {
            get {
                return ResourceManager.GetString("CarrierTransportChargesSettlementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载重 的本地化字符串。
        /// </summary>
        public static string CarryingCapacity {
            get {
                return ResourceManager.GetString("CarryingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型 的本地化字符串。
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算符 的本地化字符串。
        /// </summary>
        public static string CompareOperator {
            get {
                return ResourceManager.GetString("CompareOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件组合表达式 的本地化字符串。
        /// </summary>
        public static string ConditionExpression {
            get {
                return ResourceManager.GetString("ConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件编码 的本地化字符串。
        /// </summary>
        public static string ConditionId {
            get {
                return ResourceManager.GetString("ConditionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件序号 的本地化字符串。
        /// </summary>
        public static string ConditionNum {
            get {
                return ResourceManager.GetString("ConditionNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理条件 的本地化字符串。
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄库交货单号 的本地化字符串。
        /// </summary>
        public static string ConsignedDeliveryNo {
            get {
                return ResourceManager.GetString("ConsignedDeliveryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人姓名 的本地化字符串。
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人电话 的本地化字符串。
        /// </summary>
        public static string ContactTel {
            get {
                return ResourceManager.GetString("ContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同编码 的本地化字符串。
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同号 的本地化字符串。
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折算系数 的本地化字符串。
        /// </summary>
        public static string ConvertCoefficient {
            get {
                return ResourceManager.GetString("ConvertCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家 的本地化字符串。
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入时间 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户全称 的本地化字符串。
        /// </summary>
        public static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户编码 的本地化字符串。
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算运费 的本地化字符串。
        /// </summary>
        public static string CustomerTransportCharges {
            get {
                return ResourceManager.GetString("CustomerTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算记录编码 的本地化字符串。
        /// </summary>
        public static string CustomerTransportChargesSettlementId {
            get {
                return ResourceManager.GetString("CustomerTransportChargesSettlementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货损情况 的本地化字符串。
        /// </summary>
        public static string DamageInfo {
            get {
                return ResourceManager.GetString("DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊承运运费 的本地化字符串。
        /// </summary>
        public static string DeliverBillCarrierTransportCharges {
            get {
                return ResourceManager.GetString("DeliverBillCarrierTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊承运单价 的本地化字符串。
        /// </summary>
        public static string DeliverBillCarrierTransportPrice {
            get {
                return ResourceManager.GetString("DeliverBillCarrierTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单编码 的本地化字符串。
        /// </summary>
        public static string DeliverBillId {
            get {
                return ResourceManager.GetString("DeliverBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单号 的本地化字符串。
        /// </summary>
        public static string DeliverBillNo {
            get {
                return ResourceManager.GetString("DeliverBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单回单已收 的本地化字符串。
        /// </summary>
        public static string DeliverBillReceiptReceived {
            get {
                return ResourceManager.GetString("DeliverBillReceiptReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货日期 的本地化字符串。
        /// </summary>
        public static string DeliverDate {
            get {
                return ResourceManager.GetString("DeliverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移仓入库力支费 的本地化字符串。
        /// </summary>
        public static string DeliverEnterWarehouseForceFee {
            get {
                return ResourceManager.GetString("DeliverEnterWarehouseForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货出库力支费 的本地化字符串。
        /// </summary>
        public static string DeliverOutWarehouseForceFee {
            get {
                return ResourceManager.GetString("DeliverOutWarehouseForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库类别 的本地化字符串。
        /// </summary>
        public static string DeliverType {
            get {
                return ResourceManager.GetString("DeliverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交货单号 的本地化字符串。
        /// </summary>
        public static string DeliveryNo {
            get {
                return ResourceManager.GetString("DeliveryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交货单号 的本地化字符串。
        /// </summary>
        public static string DeliveryOrderNo {
            get {
                return ResourceManager.GetString("DeliveryOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货仓库 的本地化字符串。
        /// </summary>
        public static string DeliveryWarehouse {
            get {
                return ResourceManager.GetString("DeliveryWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讫点市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string DestCity {
            get {
                return ResourceManager.GetString("DestCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讫点国家 的本地化字符串。
        /// </summary>
        public static string DestCountry {
            get {
                return ResourceManager.GetString("DestCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讫点 的本地化字符串。
        /// </summary>
        public static string DestPlace {
            get {
                return ResourceManager.GetString("DestPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讫点省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string DestProvince {
            get {
                return ResourceManager.GetString("DestProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单编码 的本地化字符串。
        /// </summary>
        public static string DispatchBillId {
            get {
                return ResourceManager.GetString("DispatchBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单号 的本地化字符串。
        /// </summary>
        public static string DispatchBillNo {
            get {
                return ResourceManager.GetString("DispatchBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度运费 的本地化字符串。
        /// </summary>
        public static string DispatchedTransportCharges {
            get {
                return ResourceManager.GetString("DispatchedTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度单价 的本地化字符串。
        /// </summary>
        public static string DispatchedTransportPrice {
            get {
                return ResourceManager.GetString("DispatchedTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度时间 的本地化字符串。
        /// </summary>
        public static string DispatchTime {
            get {
                return ResourceManager.GetString("DispatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理人编码 的本地化字符串。
        /// </summary>
        public static string DisposerId {
            get {
                return ResourceManager.GetString("DisposerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理人姓名 的本地化字符串。
        /// </summary>
        public static string DisposerName {
            get {
                return ResourceManager.GetString("DisposerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开票人 的本地化字符串。
        /// </summary>
        public static string Drawer {
            get {
                return ResourceManager.GetString("Drawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司机姓名 的本地化字符串。
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司机手机 的本地化字符串。
        /// </summary>
        public static string DriverTel {
            get {
                return ResourceManager.GetString("DriverTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期末结存 的本地化字符串。
        /// </summary>
        public static string EndingBalance {
            get {
                return ResourceManager.GetString("EndingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止时间 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库类别 的本地化字符串。
        /// </summary>
        public static string EnterType {
            get {
                return ResourceManager.GetString("EnterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单编码 的本地化字符串。
        /// </summary>
        public static string EnterWarehouseBillId {
            get {
                return ResourceManager.GetString("EnterWarehouseBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单号 的本地化字符串。
        /// </summary>
        public static string EnterWarehouseBillNo {
            get {
                return ResourceManager.GetString("EnterWarehouseBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库时间 的本地化字符串。
        /// </summary>
        public static string EnterWarehouseTime {
            get {
                return ResourceManager.GetString("EnterWarehouseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实付金额 的本地化字符串。
        /// </summary>
        public static string FactpaymentAmount {
            get {
                return ResourceManager.GetString("FactpaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件名 的本地化字符串。
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件值 的本地化字符串。
        /// </summary>
        public static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计 的本地化字符串。
        /// </summary>
        public static string FinalTotal {
            get {
                return ResourceManager.GetString("FinalTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罚款金额 的本地化字符串。
        /// </summary>
        public static string FineAmount {
            get {
                return ResourceManager.GetString("FineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罚款时间 的本地化字符串。
        /// </summary>
        public static string FineTime {
            get {
                return ResourceManager.GetString("FineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名 的本地化字符串。
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力支费 的本地化字符串。
        /// </summary>
        public static string ForceFee {
            get {
                return ResourceManager.GetString("ForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能编码 的本地化字符串。
        /// </summary>
        public static string FuncId {
            get {
                return ResourceManager.GetString("FuncId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能名称 的本地化字符串。
        /// </summary>
        public static string FuncName {
            get {
                return ResourceManager.GetString("FuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物编码 的本地化字符串。
        /// </summary>
        public static string GoodsId {
            get {
                return ResourceManager.GetString("GoodsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物名称 的本地化字符串。
        /// </summary>
        public static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物编号 的本地化字符串。
        /// </summary>
        public static string GoodsNo {
            get {
                return ResourceManager.GetString("GoodsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 克重 的本地化字符串。
        /// </summary>
        public static string GrammeWeight {
            get {
                return ResourceManager.GetString("GrammeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毛利率 的本地化字符串。
        /// </summary>
        public static string GrossProfitRate {
            get {
                return ResourceManager.GetString("GrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毛重率 的本地化字符串。
        /// </summary>
        public static string GrossWeightRate {
            get {
                return ResourceManager.GetString("GrossWeightRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组编码 的本地化字符串。
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名称 的本地化字符串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有短驳费 的本地化字符串。
        /// </summary>
        public static string HasDrayage {
            get {
                return ResourceManager.GetString("HasDrayage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住宅电话 的本地化字符串。
        /// </summary>
        public static string HomeTel {
            get {
                return ResourceManager.GetString("HomeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录编码 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入文件示例 的本地化字符串。
        /// </summary>
        public static string ImportFileExample {
            get {
                return ResourceManager.GetString("ImportFileExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string IndentifyCode {
            get {
                return ResourceManager.GetString("IndentifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票金额 的本地化字符串。
        /// </summary>
        public static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票号码 的本地化字符串。
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开票时间 的本地化字符串。
        /// </summary>
        public static string InvoiceTime {
            get {
                return ResourceManager.GetString("InvoiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票种类 的本地化字符串。
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否注销 的本地化字符串。
        /// </summary>
        public static string IsCancel {
            get {
                return ResourceManager.GetString("IsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运运费是否结算 的本地化字符串。
        /// </summary>
        public static string IsCarrierTransportChargesSettled {
            get {
                return ResourceManager.GetString("IsCarrierTransportChargesSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否寄库 的本地化字符串。
        /// </summary>
        public static string IsConsigning {
            get {
                return ResourceManager.GetString("IsConsigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同是否冲帐 的本地化字符串。
        /// </summary>
        public static string IsContractReversed {
            get {
                return ResourceManager.GetString("IsContractReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户运费是否结算 的本地化字符串。
        /// </summary>
        public static string IsCustomerTransportChargesSettled {
            get {
                return ResourceManager.GetString("IsCustomerTransportChargesSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除 的本地化字符串。
        /// </summary>
        public static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否分期发货 的本地化字符串。
        /// </summary>
        public static string IsInstalment {
            get {
                return ResourceManager.GetString("IsInstalment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否租借 的本地化字符串。
        /// </summary>
        public static string IsLease {
            get {
                return ResourceManager.GetString("IsLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为组织部门负责人 的本地化字符串。
        /// </summary>
        public static string IsOrganLeader {
            get {
                return ResourceManager.GetString("IsOrganLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为组织部门管理人员 的本地化字符串。
        /// </summary>
        public static string IsOrganManager {
            get {
                return ResourceManager.GetString("IsOrganManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否回单 的本地化字符串。
        /// </summary>
        public static string IsReceiptReceived {
            get {
                return ResourceManager.GetString("IsReceiptReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示 的本地化字符串。
        /// </summary>
        public static string IsShow {
            get {
                return ResourceManager.GetString("IsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加盟 的本地化字符串。
        /// </summary>
        public static string JoinIn {
            get {
                return ResourceManager.GetString("JoinIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公里数 的本地化字符串。
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提货方式 的本地化字符串。
        /// </summary>
        public static string LadingType {
            get {
                return ResourceManager.GetString("LadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓 的本地化字符串。
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驾驶员证号 的本地化字符串。
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制总价 的本地化字符串。
        /// </summary>
        public static string LimitedTransportCharges {
            get {
                return ResourceManager.GetString("LimitedTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制单价 的本地化字符串。
        /// </summary>
        public static string LimitedTransportPrice {
            get {
                return ResourceManager.GetString("LimitedTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上力支费价格 的本地化字符串。
        /// </summary>
        public static string LoadingForceFeePrice {
            get {
                return ResourceManager.GetString("LoadingForceFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货位 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垛数上限 的本地化字符串。
        /// </summary>
        public static string MaxPiles {
            get {
                return ResourceManager.GetString("MaxPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吨数上限 的本地化字符串。
        /// </summary>
        public static string MaxTunnages {
            get {
                return ResourceManager.GetString("MaxTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吨数(垛数)上限 的本地化字符串。
        /// </summary>
        public static string MaxTunnagesOrPiles {
            get {
                return ResourceManager.GetString("MaxTunnagesOrPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垛数下限 的本地化字符串。
        /// </summary>
        public static string MinPiles {
            get {
                return ResourceManager.GetString("MinPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吨数下限 的本地化字符串。
        /// </summary>
        public static string MinTunnages {
            get {
                return ResourceManager.GetString("MinTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吨数(垛数)下限 的本地化字符串。
        /// </summary>
        public static string MinTunnagesOrPiles {
            get {
                return ResourceManager.GetString("MinTunnagesOrPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string MobileTel {
            get {
                return ResourceManager.GetString("MobileTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移库单编码 的本地化字符串。
        /// </summary>
        public static string MoveWarehouseBillId {
            get {
                return ResourceManager.GetString("MoveWarehouseBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移库单号 的本地化字符串。
        /// </summary>
        public static string MoveWarehouseBillNo {
            get {
                return ResourceManager.GetString("MoveWarehouseBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移库日期 的本地化字符串。
        /// </summary>
        public static string MoveWarehouseTime {
            get {
                return ResourceManager.GetString("MoveWarehouseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移入货位 的本地化字符串。
        /// </summary>
        public static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移入件数 的本地化字符串。
        /// </summary>
        public static string NewPieces {
            get {
                return ResourceManager.GetString("NewPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移入垛数 的本地化字符串。
        /// </summary>
        public static string NewPiles {
            get {
                return ResourceManager.GetString("NewPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移入万只 的本地化字符串。
        /// </summary>
        public static string NewTenThousands {
            get {
                return ResourceManager.GetString("NewTenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移入吨数 的本地化字符串。
        /// </summary>
        public static string NewTunnages {
            get {
                return ResourceManager.GetString("NewTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原货位 的本地化字符串。
        /// </summary>
        public static string OldLocation {
            get {
                return ResourceManager.GetString("OldLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原件数 的本地化字符串。
        /// </summary>
        public static string OldPieces {
            get {
                return ResourceManager.GetString("OldPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原垛数 的本地化字符串。
        /// </summary>
        public static string OldPiles {
            get {
                return ResourceManager.GetString("OldPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原万只 的本地化字符串。
        /// </summary>
        public static string OldTenThousands {
            get {
                return ResourceManager.GetString("OldTenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原吨数 的本地化字符串。
        /// </summary>
        public static string OldTunnages {
            get {
                return ResourceManager.GetString("OldTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单编号 的本地化字符串。
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织部门编码 的本地化字符串。
        /// </summary>
        public static string OrganId {
            get {
                return ResourceManager.GetString("OrganId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织部门名称 的本地化字符串。
        /// </summary>
        public static string OrganName {
            get {
                return ResourceManager.GetString("OrganName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织部门类别 的本地化字符串。
        /// </summary>
        public static string OrganType {
            get {
                return ResourceManager.GetString("OrganType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始合同号 的本地化字符串。
        /// </summary>
        public static string OriginalContractNo {
            get {
                return ResourceManager.GetString("OriginalContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库单编码 的本地化字符串。
        /// </summary>
        public static string OutWarehouseBillId {
            get {
                return ResourceManager.GetString("OutWarehouseBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库单号 的本地化字符串。
        /// </summary>
        public static string OutWarehouseBillNo {
            get {
                return ResourceManager.GetString("OutWarehouseBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库日期 的本地化字符串。
        /// </summary>
        public static string OutWarehouseTime {
            get {
                return ResourceManager.GetString("OutWarehouseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库单位 的本地化字符串。
        /// </summary>
        public static string OutWarehouseUnit {
            get {
                return ResourceManager.GetString("OutWarehouseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出百分比 的本地化字符串。
        /// </summary>
        public static string OverPercentage {
            get {
                return ResourceManager.GetString("OverPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门或办事处编码 的本地化字符串。
        /// </summary>
        public static string OwnOrganId {
            get {
                return ResourceManager.GetString("OwnOrganId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门或办事处 的本地化字符串。
        /// </summary>
        public static string OwnOrganName {
            get {
                return ResourceManager.GetString("OwnOrganName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装 的本地化字符串。
        /// </summary>
        public static string PackingSpecification {
            get {
                return ResourceManager.GetString("PackingSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装样式 的本地化字符串。
        /// </summary>
        public static string PackingStyle {
            get {
                return ResourceManager.GetString("PackingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共{0}页 的本地化字符串。
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 的本地化字符串。
        /// </summary>
        public static string PageNo {
            get {
                return ResourceManager.GetString("PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级组织部门 的本地化字符串。
        /// </summary>
        public static string ParentOrgan {
            get {
                return ResourceManager.GetString("ParentOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父类别名称 的本地化字符串。
        /// </summary>
        public static string ParentTypeName {
            get {
                return ResourceManager.GetString("ParentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款单位编码 的本地化字符串。
        /// </summary>
        public static string PayerId {
            get {
                return ResourceManager.GetString("PayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款单位名称 的本地化字符串。
        /// </summary>
        public static string PayerName {
            get {
                return ResourceManager.GetString("PayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算方式 的本地化字符串。
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件数 的本地化字符串。
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件数/箱数 的本地化字符串。
        /// </summary>
        public static string PiecesOrBoxes {
            get {
                return ResourceManager.GetString("PiecesOrBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件重 的本地化字符串。
        /// </summary>
        public static string PieceWeight {
            get {
                return ResourceManager.GetString("PieceWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件重/折算系数 的本地化字符串。
        /// </summary>
        public static string PieceWeightOrConvertCoefficient {
            get {
                return ResourceManager.GetString("PieceWeightOrConvertCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垛数 的本地化字符串。
        /// </summary>
        public static string Piles {
            get {
                return ResourceManager.GetString("Piles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划编码 的本地化字符串。
        /// </summary>
        public static string PlanId {
            get {
                return ResourceManager.GetString("PlanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划单号 的本地化字符串。
        /// </summary>
        public static string PlanNo {
            get {
                return ResourceManager.GetString("PlanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划状态 的本地化字符串。
        /// </summary>
        public static string PlanState {
            get {
                return ResourceManager.GetString("PlanState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划类别 的本地化字符串。
        /// </summary>
        public static string PlanType {
            get {
                return ResourceManager.GetString("PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位编码 的本地化字符串。
        /// </summary>
        public static string PositionId {
            get {
                return ResourceManager.GetString("PositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位名称 的本地化字符串。
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政编码 的本地化字符串。
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预付运费 的本地化字符串。
        /// </summary>
        public static string PrepayTransportCharges {
            get {
                return ResourceManager.GetString("PrepayTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配载 的本地化字符串。
        /// </summary>
        public static string Prestowage {
            get {
                return ResourceManager.GetString("Prestowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产日期 的本地化字符串。
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已回单 的本地化字符串。
        /// </summary>
        public static string ReceiptReceived {
            get {
                return ResourceManager.GetString("ReceiptReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位地址 的本地化字符串。
        /// </summary>
        public static string ReceiverAddress {
            get {
                return ResourceManager.GetString("ReceiverAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位所在市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string ReceiverCity {
            get {
                return ResourceManager.GetString("ReceiverCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位联系人 的本地化字符串。
        /// </summary>
        public static string ReceiverContact {
            get {
                return ResourceManager.GetString("ReceiverContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位联系电话 的本地化字符串。
        /// </summary>
        public static string ReceiverContactTel {
            get {
                return ResourceManager.GetString("ReceiverContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位所在国家 的本地化字符串。
        /// </summary>
        public static string ReceiverCountry {
            get {
                return ResourceManager.GetString("ReceiverCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位编码 的本地化字符串。
        /// </summary>
        public static string ReceiverId {
            get {
                return ResourceManager.GetString("ReceiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位名称 的本地化字符串。
        /// </summary>
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位所在省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string ReceiverProvince {
            get {
                return ResourceManager.GetString("ReceiverProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货单位签收 的本地化字符串。
        /// </summary>
        public static string ReceiverSign {
            get {
                return ResourceManager.GetString("ReceiverSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货方式 的本地化字符串。
        /// </summary>
        public static string ReceiveType {
            get {
                return ResourceManager.GetString("ReceiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余冲帐金额 的本地化字符串。
        /// </summary>
        public static string ResidualReverseAmount {
            get {
                return ResourceManager.GetString("ResidualReverseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余运费 的本地化字符串。
        /// </summary>
        public static string ResidualTransportCharges {
            get {
                return ResourceManager.GetString("ResidualTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回单时间 的本地化字符串。
        /// </summary>
        public static string ReturnTime {
            get {
                return ResourceManager.GetString("ReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐金额 的本地化字符串。
        /// </summary>
        public static string ReverseAmount {
            get {
                return ResourceManager.GetString("ReverseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已冲帐金额 的本地化字符串。
        /// </summary>
        public static string ReversedAmount {
            get {
                return ResourceManager.GetString("ReversedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐记录编码 的本地化字符串。
        /// </summary>
        public static string ReverseId {
            get {
                return ResourceManager.GetString("ReverseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐人编码 的本地化字符串。
        /// </summary>
        public static string ReverserId {
            get {
                return ResourceManager.GetString("ReverserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐人姓名 的本地化字符串。
        /// </summary>
        public static string ReverserName {
            get {
                return ResourceManager.GetString("ReverserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐时间 的本地化字符串。
        /// </summary>
        public static string ReverseTime {
            get {
                return ResourceManager.GetString("ReverseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过江费 的本地化字符串。
        /// </summary>
        public static string RiverCrossingCharges {
            get {
                return ResourceManager.GetString("RiverCrossingCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自营 的本地化字符串。
        /// </summary>
        public static string SelfSupport {
            get {
                return ResourceManager.GetString("SelfSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ~ 的本地化字符串。
        /// </summary>
        public static string Separator1 {
            get {
                return ResourceManager.GetString("Separator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算金额 的本地化字符串。
        /// </summary>
        public static string SettlementAmount {
            get {
                return ResourceManager.GetString("SettlementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算公式 的本地化字符串。
        /// </summary>
        public static string SettlementExpression {
            get {
                return ResourceManager.GetString("SettlementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算时间 的本地化字符串。
        /// </summary>
        public static string SettlementTime {
            get {
                return ResourceManager.GetString("SettlementTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出仓单货物编码 的本地化字符串。
        /// </summary>
        public static string ShipmentBillGoodsIds {
            get {
                return ResourceManager.GetString("ShipmentBillGoodsIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出仓单编码 的本地化字符串。
        /// </summary>
        public static string ShipmentBillId {
            get {
                return ResourceManager.GetString("ShipmentBillId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出仓单号 的本地化字符串。
        /// </summary>
        public static string ShipmentBillNo {
            get {
                return ResourceManager.GetString("ShipmentBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出货日期 的本地化字符串。
        /// </summary>
        public static string ShipmentDate {
            get {
                return ResourceManager.GetString("ShipmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装运单号 的本地化字符串。
        /// </summary>
        public static string ShipmentNo {
            get {
                return ResourceManager.GetString("ShipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装运时间 的本地化字符串。
        /// </summary>
        public static string ShipmentTime {
            get {
                return ResourceManager.GetString("ShipmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送达方 的本地化字符串。
        /// </summary>
        public static string ShiptoParty {
            get {
                return ResourceManager.GetString("ShiptoParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格型号 的本地化字符串。
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工编码 的本地化字符串。
        /// </summary>
        public static string StaffId {
            get {
                return ResourceManager.GetString("StaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工姓名 的本地化字符串。
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string StartCity {
            get {
                return ResourceManager.GetString("StartCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点国家 的本地化字符串。
        /// </summary>
        public static string StartCountry {
            get {
                return ResourceManager.GetString("StartCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点 的本地化字符串。
        /// </summary>
        public static string StartPlace {
            get {
                return ResourceManager.GetString("StartPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string StartProvince {
            get {
                return ResourceManager.GetString("StartProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤编码 的本地化字符串。
        /// </summary>
        public static string StepId {
            get {
                return ResourceManager.GetString("StepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤名称 的本地化字符串。
        /// </summary>
        public static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤序号 的本地化字符串。
        /// </summary>
        public static string StepNum {
            get {
                return ResourceManager.GetString("StepNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止发货库存 的本地化字符串。
        /// </summary>
        public static string StopStock {
            get {
                return ResourceManager.GetString("StopStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓储费 的本地化字符串。
        /// </summary>
        public static string StorageFee {
            get {
                return ResourceManager.GetString("StorageFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓储费价格 的本地化字符串。
        /// </summary>
        public static string StorageFeePrice {
            get {
                return ResourceManager.GetString("StorageFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小计 的本地化字符串。
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分机 的本地化字符串。
        /// </summary>
        public static string TelExt {
            get {
                return ResourceManager.GetString("TelExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 万只 的本地化字符串。
        /// </summary>
        public static string TenThousands {
            get {
                return ResourceManager.GetString("TenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期间 的本地化字符串。
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计划拨入库 的本地化字符串。
        /// </summary>
        public static string TotalAllocateEnterWarehouse {
            get {
                return ResourceManager.GetString("TotalAllocateEnterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计划拨入库吨数 的本地化字符串。
        /// </summary>
        public static string TotalAllocateEnterWarehouseTunnages {
            get {
                return ResourceManager.GetString("TotalAllocateEnterWarehouseTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计划拨出库 的本地化字符串。
        /// </summary>
        public static string TotalAllocateOutWarehouse {
            get {
                return ResourceManager.GetString("TotalAllocateOutWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计划拨出库吨数 的本地化字符串。
        /// </summary>
        public static string TotalAllocateOutWarehouseTunnages {
            get {
                return ResourceManager.GetString("TotalAllocateOutWarehouseTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计审批运费 的本地化字符串。
        /// </summary>
        public static string TotalApproveTransportCharges {
            get {
                return ResourceManager.GetString("TotalApproveTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计承运运费 的本地化字符串。
        /// </summary>
        public static string TotalCarrierTransportCharges {
            get {
                return ResourceManager.GetString("TotalCarrierTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计结算运费 的本地化字符串。
        /// </summary>
        public static string TotalCustomerTransportCharges {
            get {
                return ResourceManager.GetString("TotalCustomerTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计移仓入库 的本地化字符串。
        /// </summary>
        public static string TotalDeliverEnterWarehouse {
            get {
                return ResourceManager.GetString("TotalDeliverEnterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计发货出库 的本地化字符串。
        /// </summary>
        public static string TotalDeliverOutWarehouse {
            get {
                return ResourceManager.GetString("TotalDeliverOutWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计入库 的本地化字符串。
        /// </summary>
        public static string TotalEnterWarehouse {
            get {
                return ResourceManager.GetString("TotalEnterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计毛利率 的本地化字符串。
        /// </summary>
        public static string TotalGrossProfitRate {
            get {
                return ResourceManager.GetString("TotalGrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计出库 的本地化字符串。
        /// </summary>
        public static string TotalOutWarehouse {
            get {
                return ResourceManager.GetString("TotalOutWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计件数 的本地化字符串。
        /// </summary>
        public static string TotalPackages {
            get {
                return ResourceManager.GetString("TotalPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计垛数 的本地化字符串。
        /// </summary>
        public static string TotalPiles {
            get {
                return ResourceManager.GetString("TotalPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计万只 的本地化字符串。
        /// </summary>
        public static string TotalTenThousands {
            get {
                return ResourceManager.GetString("TotalTenThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计运费 的本地化字符串。
        /// </summary>
        public static string TotalTransportCharges {
            get {
                return ResourceManager.GetString("TotalTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计价差 的本地化字符串。
        /// </summary>
        public static string TotalTransportChargesDifference {
            get {
                return ResourceManager.GetString("TotalTransportChargesDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 累计吨数 的本地化字符串。
        /// </summary>
        public static string TotalTunnages {
            get {
                return ResourceManager.GetString("TotalTunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂车号码 的本地化字符串。
        /// </summary>
        public static string TrailerLicenseNo {
            get {
                return ResourceManager.GetString("TrailerLicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂号 的本地化字符串。
        /// </summary>
        public static string TrailerNo {
            get {
                return ResourceManager.GetString("TrailerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人 的本地化字符串。
        /// </summary>
        public static string TransactorName {
            get {
                return ResourceManager.GetString("TransactorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费公式 的本地化字符串。
        /// </summary>
        public static string TransportChargeExpression {
            get {
                return ResourceManager.GetString("TransportChargeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费 的本地化字符串。
        /// </summary>
        public static string TransportCharges {
            get {
                return ResourceManager.GetString("TransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费差额 的本地化字符串。
        /// </summary>
        public static string TransportChargesBalance {
            get {
                return ResourceManager.GetString("TransportChargesBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价差 的本地化字符串。
        /// </summary>
        public static string TransportChargesDifference {
            get {
                return ResourceManager.GetString("TransportChargesDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价 的本地化字符串。
        /// </summary>
        public static string TransportPrice {
            get {
                return ResourceManager.GetString("TransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价公式 的本地化字符串。
        /// </summary>
        public static string TransportPriceExpression {
            get {
                return ResourceManager.GetString("TransportPriceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吨数 的本地化字符串。
        /// </summary>
        public static string Tunnages {
            get {
                return ResourceManager.GetString("Tunnages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别编码 的本地化字符串。
        /// </summary>
        public static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别名称 的本地化字符串。
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下力支费价格 的本地化字符串。
        /// </summary>
        public static string UnloadingForceFeePrice {
            get {
                return ResourceManager.GetString("UnloadingForceFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件名 的本地化字符串。
        /// </summary>
        public static string UploadFileName {
            get {
                return ResourceManager.GetString("UploadFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计价模式 的本地化字符串。
        /// </summary>
        public static string ValuationMode {
            get {
                return ResourceManager.GetString("ValuationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库 的本地化字符串。
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒结算库存 的本地化字符串。
        /// </summary>
        public static string WarningStock {
            get {
                return ResourceManager.GetString("WarningStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣款金额 的本地化字符串。
        /// </summary>
        public static string WithholdAmount {
            get {
                return ResourceManager.GetString("WithholdAmount", resourceCulture);
            }
        }
    }
}
