//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSoft.LS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSoft.LS.Resources.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批 的本地化字符串。
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批合同 的本地化字符串。
        /// </summary>
        public static string ApproveContracts {
            get {
                return ResourceManager.GetString("ApproveContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批发货计划 的本地化字符串。
        /// </summary>
        public static string ApproveDeliverPlans {
            get {
                return ResourceManager.GetString("ApproveDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配权限 的本地化字符串。
        /// </summary>
        public static string AssignPermissions {
            get {
                return ResourceManager.GetString("AssignPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合同管理 的本地化字符串。
        /// </summary>
        public static string ContractManage {
            get {
                return ResourceManager.GetString("ContractManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户审批纸发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerApprovePaperPlans {
            get {
                return ResourceManager.GetString("CustomerApprovePaperPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户录入纸直发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerNewNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("CustomerNewNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户录入纸发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerNewPaperPlan {
            get {
                return ResourceManager.GetString("CustomerNewPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货管理 的本地化字符串。
        /// </summary>
        public static string DeliveryManage {
            get {
                return ResourceManager.GetString("DeliveryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不同意 的本地化字符串。
        /// </summary>
        public static string Disagree {
            get {
                return ResourceManager.GetString("Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度 的本地化字符串。
        /// </summary>
        public static string Dispatch {
            get {
                return ResourceManager.GetString("Dispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度管理 的本地化字符串。
        /// </summary>
        public static string DispatchManage {
            get {
                return ResourceManager.GetString("DispatchManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度计划 的本地化字符串。
        /// </summary>
        public static string DispatchPlans {
            get {
                return ResourceManager.GetString("DispatchPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇总收发存 的本地化字符串。
        /// </summary>
        public static string EnterOutBalanceSummary {
            get {
                return ResourceManager.GetString("EnterOutBalanceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差入库 的本地化字符串。
        /// </summary>
        public static string EnterStockEndDifferences {
            get {
                return ResourceManager.GetString("EnterStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物入库 的本地化字符串。
        /// </summary>
        public static string EnterWarehouse {
            get {
                return ResourceManager.GetString("EnterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罚款处理 的本地化字符串。
        /// </summary>
        public static string FineContracts {
            get {
                return ResourceManager.GetString("FineContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物移库 的本地化字符串。
        /// </summary>
        public static string MoveWarehouse {
            get {
                return ResourceManager.GetString("MoveWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入罐发货计划 的本地化字符串。
        /// </summary>
        public static string NewCanPlan {
            get {
                return ResourceManager.GetString("NewCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入合同 的本地化字符串。
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入特殊承运价格 的本地化字符串。
        /// </summary>
        public static string NewDeliverBillCarrierTransportPrice {
            get {
                return ResourceManager.GetString("NewDeliverBillCarrierTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入特殊结算价格 的本地化字符串。
        /// </summary>
        public static string NewDeliverBillCustomerTransportPrice {
            get {
                return ResourceManager.GetString("NewDeliverBillCustomerTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开票 的本地化字符串。
        /// </summary>
        public static string NewInvoice {
            get {
                return ResourceManager.GetString("NewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入方便面发货计划 的本地化字符串。
        /// </summary>
        public static string NewNoodlePlan {
            get {
                return ResourceManager.GetString("NewNoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入罐直发货计划 的本地化字符串。
        /// </summary>
        public static string NewNotDeliverCanPlan {
            get {
                return ResourceManager.GetString("NewNotDeliverCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入纸直发货计划 的本地化字符串。
        /// </summary>
        public static string NewNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("NewNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入其它发货计划 的本地化字符串。
        /// </summary>
        public static string NewOtherPlan {
            get {
                return ResourceManager.GetString("NewOtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入纸发货计划 的本地化字符串。
        /// </summary>
        public static string NewPaperPlan {
            get {
                return ResourceManager.GetString("NewPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差出库 的本地化字符串。
        /// </summary>
        public static string OutStockEndDifferences {
            get {
                return ResourceManager.GetString("OutStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物出库 的本地化字符串。
        /// </summary>
        public static string OutWarehouse {
            get {
                return ResourceManager.GetString("OutWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划管理 的本地化字符串。
        /// </summary>
        public static string PlanManage {
            get {
                return ResourceManager.GetString("PlanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印划拨出仓单 的本地化字符串。
        /// </summary>
        public static string PrintAllocateShipmentBills {
            get {
                return ResourceManager.GetString("PrintAllocateShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印合同 的本地化字符串。
        /// </summary>
        public static string PrintContracts {
            get {
                return ResourceManager.GetString("PrintContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印送货单 的本地化字符串。
        /// </summary>
        public static string PrintDeliverBills {
            get {
                return ResourceManager.GetString("PrintDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印调度出仓单 的本地化字符串。
        /// </summary>
        public static string PrintDispatchedShipmentBills {
            get {
                return ResourceManager.GetString("PrintDispatchedShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印盘点表 的本地化字符串。
        /// </summary>
        public static string PrintStocktaking {
            get {
                return ResourceManager.GetString("PrintStocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回单 的本地化字符串。
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收送货单回单 的本地化字符串。
        /// </summary>
        public static string ReceiptDeliverBills {
            get {
                return ResourceManager.GetString("ReceiptDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新调度 的本地化字符串。
        /// </summary>
        public static string Redispatch {
            get {
                return ResourceManager.GetString("Redispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补打送货单 的本地化字符串。
        /// </summary>
        public static string ReprintDeliverBills {
            get {
                return ResourceManager.GetString("ReprintDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补打出仓单 的本地化字符串。
        /// </summary>
        public static string ReprintShipmentBills {
            get {
                return ResourceManager.GetString("ReprintShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化密码 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回修改 的本地化字符串。
        /// </summary>
        public static string ReturnModify {
            get {
                return ResourceManager.GetString("ReturnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐 的本地化字符串。
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐处理 的本地化字符串。
        /// </summary>
        public static string ReverseContracts {
            get {
                return ResourceManager.GetString("ReverseContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询承运单位运费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchCarrierTransportChargesSettlements {
            get {
                return ResourceManager.GetString("SearchCarrierTransportChargesSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询寄库计划 的本地化字符串。
        /// </summary>
        public static string SearchConsigningDeliverPlans {
            get {
                return ResourceManager.GetString("SearchConsigningDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询合同审批信息 的本地化字符串。
        /// </summary>
        public static string SearchContracts {
            get {
                return ResourceManager.GetString("SearchContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询客户运费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchCustomerTransportChargesSettlements {
            get {
                return ResourceManager.GetString("SearchCustomerTransportChargesSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询特殊承运价格记录 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillCarrierTransportPrices {
            get {
                return ResourceManager.GetString("SearchDeliverBillCarrierTransportPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询特殊结算价格记录 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillCustomerTransportPrices {
            get {
                return ResourceManager.GetString("SearchDeliverBillCustomerTransportPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询送货单回单 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillReceipts {
            get {
                return ResourceManager.GetString("SearchDeliverBillReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询送货单 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBills {
            get {
                return ResourceManager.GetString("SearchDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询入库记录 的本地化字符串。
        /// </summary>
        public static string SearchEnterWarehouseBills {
            get {
                return ResourceManager.GetString("SearchEnterWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询罚款记录 的本地化字符串。
        /// </summary>
        public static string SearchFines {
            get {
                return ResourceManager.GetString("SearchFines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询移库记录 的本地化字符串。
        /// </summary>
        public static string SearchMoveWarehouseBills {
            get {
                return ResourceManager.GetString("SearchMoveWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询出库记录 的本地化字符串。
        /// </summary>
        public static string SearchOutWarehouseBills {
            get {
                return ResourceManager.GetString("SearchOutWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询计划 的本地化字符串。
        /// </summary>
        public static string SearchPlans {
            get {
                return ResourceManager.GetString("SearchPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询冲帐记录 的本地化字符串。
        /// </summary>
        public static string SearchReverses {
            get {
                return ResourceManager.GetString("SearchReverses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询库存尾差 的本地化字符串。
        /// </summary>
        public static string SearchStockEndDifferences {
            get {
                return ResourceManager.GetString("SearchStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询仓储力支费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchStorageAndForceFeeSettlements {
            get {
                return ResourceManager.GetString("SearchStorageAndForceFeeSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置登录帐号 的本地化字符串。
        /// </summary>
        public static string SetAccount {
            get {
                return ResourceManager.GetString("SetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置承运单位档案 的本地化字符串。
        /// </summary>
        public static string SetCarrier {
            get {
                return ResourceManager.GetString("SetCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string SetCity {
            get {
                return ResourceManager.GetString("SetCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置客户联络人 的本地化字符串。
        /// </summary>
        public static string SetContact {
            get {
                return ResourceManager.GetString("SetContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置国家 的本地化字符串。
        /// </summary>
        public static string SetCountry {
            get {
                return ResourceManager.GetString("SetCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置客户档案 的本地化字符串。
        /// </summary>
        public static string SetCustomer {
            get {
                return ResourceManager.GetString("SetCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置客户类别 的本地化字符串。
        /// </summary>
        public static string SetCustomerType {
            get {
                return ResourceManager.GetString("SetCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置驾驶员档案 的本地化字符串。
        /// </summary>
        public static string SetDriver {
            get {
                return ResourceManager.GetString("SetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置货物档案 的本地化字符串。
        /// </summary>
        public static string SetGoods {
            get {
                return ResourceManager.GetString("SetGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置货物类别 的本地化字符串。
        /// </summary>
        public static string SetGoodsType {
            get {
                return ResourceManager.GetString("SetGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置行业 的本地化字符串。
        /// </summary>
        public static string SetIndustry {
            get {
                return ResourceManager.GetString("SetIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置组织结构 的本地化字符串。
        /// </summary>
        public static string SetOrganization {
            get {
                return ResourceManager.GetString("SetOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置权限组 的本地化字符串。
        /// </summary>
        public static string SetPermissionGroup {
            get {
                return ResourceManager.GetString("SetPermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置计划审批流程 的本地化字符串。
        /// </summary>
        public static string SetPlanApproveFlow {
            get {
                return ResourceManager.GetString("SetPlanApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置岗位 的本地化字符串。
        /// </summary>
        public static string SetPosition {
            get {
                return ResourceManager.GetString("SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置价格审批流程 的本地化字符串。
        /// </summary>
        public static string SetPriceApproveFlow {
            get {
                return ResourceManager.GetString("SetPriceApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string SetProvince {
            get {
                return ResourceManager.GetString("SetProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置收货单位档案 的本地化字符串。
        /// </summary>
        public static string SetReceiver {
            get {
                return ResourceManager.GetString("SetReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置员工档案 的本地化字符串。
        /// </summary>
        public static string SetStaff {
            get {
                return ResourceManager.GetString("SetStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算 的本地化字符串。
        /// </summary>
        public static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费结算 的本地化字符串。
        /// </summary>
        public static string SettlementManage {
            get {
                return ResourceManager.GetString("SettlementManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置运费限价 的本地化字符串。
        /// </summary>
        public static string SetTransportLimitedPrice {
            get {
                return ResourceManager.GetString("SetTransportLimitedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置仓库 的本地化字符串。
        /// </summary>
        public static string SetWarehouse {
            get {
                return ResourceManager.GetString("SetWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运单位对帐 的本地化字符串。
        /// </summary>
        public static string StatCarrierStatement {
            get {
                return ResourceManager.GetString("StatCarrierStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户对帐 的本地化字符串。
        /// </summary>
        public static string StatCustomerStatement {
            get {
                return ResourceManager.GetString("StatCustomerStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计客户总产值 的本地化字符串。
        /// </summary>
        public static string StatCustomerTotalOutput {
            get {
                return ResourceManager.GetString("StatCustomerTotalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据统计 的本地化字符串。
        /// </summary>
        public static string StatisticsManage {
            get {
                return ResourceManager.GetString("StatisticsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计办事处毛利率 的本地化字符串。
        /// </summary>
        public static string StatOrganGrossProfitRate {
            get {
                return ResourceManager.GetString("StatOrganGrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计办事处总产值 的本地化字符串。
        /// </summary>
        public static string StatOrganTotalOutput {
            get {
                return ResourceManager.GetString("StatOrganTotalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计仓储力支费 的本地化字符串。
        /// </summary>
        public static string StatStorageAndForceFee {
            get {
                return ResourceManager.GetString("StatStorageAndForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交合同 的本地化字符串。
        /// </summary>
        public static string SubmitContracts {
            get {
                return ResourceManager.GetString("SubmitContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交计划 的本地化字符串。
        /// </summary>
        public static string SubmitDeliverPlans {
            get {
                return ResourceManager.GetString("SubmitDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交调度单 的本地化字符串。
        /// </summary>
        public static string SubmitDispatchBills {
            get {
                return ResourceManager.GetString("SubmitDispatchBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交出仓单 的本地化字符串。
        /// </summary>
        public static string SubmitShipmentBills {
            get {
                return ResourceManager.GetString("SubmitShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综合查询 的本地化字符串。
        /// </summary>
        public static string SyntheticalSearch {
            get {
                return ResourceManager.GetString("SyntheticalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string SystemManage {
            get {
                return ResourceManager.GetString("SystemManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓储管理 的本地化字符串。
        /// </summary>
        public static string WarehouseManage {
            get {
                return ResourceManager.GetString("WarehouseManage", resourceCulture);
            }
        }
    }
}
