//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSoft.LS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Options {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSoft.LS.Resources.Options", typeof(Options).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 划拨出库 的本地化字符串。
        /// </summary>
        public static string AllocateGoods {
            get {
                return ResourceManager.GetString("AllocateGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 划拨入库 的本地化字符串。
        /// </summary>
        public static string AllocateInStorage {
            get {
                return ResourceManager.GetString("AllocateInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审批 的本地化字符串。
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罐 的本地化字符串。
        /// </summary>
        public static string CanPlan {
            get {
                return ResourceManager.GetString("CanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现付 的本地化字符串。
        /// </summary>
        public static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string Contain {
            get {
                return ResourceManager.GetString("Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差出库 的本地化字符串。
        /// </summary>
        public static string DeliverEndDifferences {
            get {
                return ResourceManager.GetString("DeliverEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货出库 的本地化字符串。
        /// </summary>
        public static string DeliverGoods {
            get {
                return ResourceManager.GetString("DeliverGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移仓入库 的本地化字符串。
        /// </summary>
        public static string DeliverInStorage {
            get {
                return ResourceManager.GetString("DeliverInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差入库 的本地化字符串。
        /// </summary>
        public static string EndDifferencesInStorage {
            get {
                return ResourceManager.GetString("EndDifferencesInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于或等于 的本地化字符串。
        /// </summary>
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按批次号分组合计 的本地化字符串。
        /// </summary>
        public static string GroupByBatchNo {
            get {
                return ResourceManager.GetString("GroupByBatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按客户名称分组合计 的本地化字符串。
        /// </summary>
        public static string GroupByCustomerName {
            get {
                return ResourceManager.GetString("GroupByCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按货位分组合计 的本地化字符串。
        /// </summary>
        public static string GroupByLocation {
            get {
                return ResourceManager.GetString("GroupByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按仓库分组合计 的本地化字符串。
        /// </summary>
        public static string GroupByWarehouse {
            get {
                return ResourceManager.GetString("GroupByWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有令 的本地化字符串。
        /// </summary>
        public static string HaveReam {
            get {
                return ResourceManager.GetString("HaveReam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加盟 的本地化字符串。
        /// </summary>
        public static string JoinIn {
            get {
                return ResourceManager.GetString("JoinIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于或等于 的本地化字符串。
        /// </summary>
        public static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月结 的本地化字符串。
        /// </summary>
        public static string MonthlyStatement {
            get {
                return ResourceManager.GetString("MonthlyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -新驾驶员- 的本地化字符串。
        /// </summary>
        public static string NewDriver {
            get {
                return ResourceManager.GetString("NewDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方便面 的本地化字符串。
        /// </summary>
        public static string NoodlePlan {
            get {
                return ResourceManager.GetString("NoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无令 的本地化字符串。
        /// </summary>
        public static string NoReam {
            get {
                return ResourceManager.GetString("NoReam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        public static string NotContain {
            get {
                return ResourceManager.GetString("NotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罐直发 的本地化字符串。
        /// </summary>
        public static string NotDeliverCanPlan {
            get {
                return ResourceManager.GetString("NotDeliverCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸直发 的本地化字符串。
        /// </summary>
        public static string NotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("NotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        public static string OtherPlan {
            get {
                return ResourceManager.GetString("OtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出金额 的本地化字符串。
        /// </summary>
        public static string OverAmount {
            get {
                return ResourceManager.GetString("OverAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出百分比 的本地化字符串。
        /// </summary>
        public static string OverPercentage {
            get {
                return ResourceManager.GetString("OverPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸 的本地化字符串。
        /// </summary>
        public static string PaperPlan {
            get {
                return ResourceManager.GetString("PaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配送 的本地化字符串。
        /// </summary>
        public static string PickUpDelivery {
            get {
                return ResourceManager.GetString("PickUpDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自提 的本地化字符串。
        /// </summary>
        public static string PickUpSelf {
            get {
                return ResourceManager.GetString("PickUpSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通发票 的本地化字符串。
        /// </summary>
        public static string PlainInvoice {
            get {
                return ResourceManager.GetString("PlainInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划审批 的本地化字符串。
        /// </summary>
        public static string PlanApproveFlow {
            get {
                return ResourceManager.GetString("PlanApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配载 的本地化字符串。
        /// </summary>
        public static string Prestowage {
            get {
                return ResourceManager.GetString("Prestowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格审批 的本地化字符串。
        /// </summary>
        public static string PriceApproveFlow {
            get {
                return ResourceManager.GetString("PriceApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -选择车号- 的本地化字符串。
        /// </summary>
        public static string SelectCarNo {
            get {
                return ResourceManager.GetString("SelectCarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -选择国家- 的本地化字符串。
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -选择货物类别- 的本地化字符串。
        /// </summary>
        public static string SelectGoodsType {
            get {
                return ResourceManager.GetString("SelectGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -选择省／州／区／直辖市- 的本地化字符串。
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自营 的本地化字符串。
        /// </summary>
        public static string SelfSupport {
            get {
                return ResourceManager.GetString("SelfSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工 的本地化字符串。
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分公司 的本地化字符串。
        /// </summary>
        public static string Subsidiary {
            get {
                return ResourceManager.GetString("Subsidiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按交货单吨数计价 的本地化字符串。
        /// </summary>
        public static string ValuationMode1 {
            get {
                return ResourceManager.GetString("ValuationMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按装运单总吨数计价 的本地化字符串。
        /// </summary>
        public static string ValuationMode2 {
            get {
                return ResourceManager.GetString("ValuationMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按同日同地总发货吨数计价 的本地化字符串。
        /// </summary>
        public static string ValuationMode3 {
            get {
                return ResourceManager.GetString("ValuationMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厢车 的本地化字符串。
        /// </summary>
        public static string VanTruck {
            get {
                return ResourceManager.GetString("VanTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增值税发票 的本地化字符串。
        /// </summary>
        public static string VatInvoice {
            get {
                return ResourceManager.GetString("VatInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 板车 的本地化字符串。
        /// </summary>
        public static string WoodenHandCart {
            get {
                return ResourceManager.GetString("WoodenHandCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作组 的本地化字符串。
        /// </summary>
        public static string WorkingGroup {
            get {
                return ResourceManager.GetString("WorkingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
