//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSoft.LS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tabs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tabs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSoft.LS.Resources.Tabs", typeof(Tabs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 审批记录列表 的本地化字符串。
        /// </summary>
        public static string ApproveOpinionList {
            get {
                return ResourceManager.GetString("ApproveOpinionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆信息 的本地化字符串。
        /// </summary>
        public static string CarInfo {
            get {
                return ResourceManager.GetString("CarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆列表 的本地化字符串。
        /// </summary>
        public static string CarList {
            get {
                return ResourceManager.GetString("CarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件列表 的本地化字符串。
        /// </summary>
        public static string ConditionList {
            get {
                return ResourceManager.GetString("ConditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单列表 的本地化字符串。
        /// </summary>
        public static string DeliverBillList {
            get {
                return ResourceManager.GetString("DeliverBillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货列表 的本地化字符串。
        /// </summary>
        public static string DeliveryList {
            get {
                return ResourceManager.GetString("DeliveryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待调度计划列表 的本地化字符串。
        /// </summary>
        public static string DispatchDeliverPlanList {
            get {
                return ResourceManager.GetString("DispatchDeliverPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已配载计划列表 的本地化字符串。
        /// </summary>
        public static string DispatchedDeliverPlanList {
            get {
                return ResourceManager.GetString("DispatchedDeliverPlanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已配载货物列表 的本地化字符串。
        /// </summary>
        public static string DispatchedGoodsList {
            get {
                return ResourceManager.GetString("DispatchedGoodsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待调度货物列表 的本地化字符串。
        /// </summary>
        public static string DispatchGoodsList {
            get {
                return ResourceManager.GetString("DispatchGoodsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离列表 的本地化字符串。
        /// </summary>
        public static string DistanceList {
            get {
                return ResourceManager.GetString("DistanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驾驶员列表 的本地化字符串。
        /// </summary>
        public static string DriverList {
            get {
                return ResourceManager.GetString("DriverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力支费价格列表 的本地化字符串。
        /// </summary>
        public static string ForceFeePriceList {
            get {
                return ResourceManager.GetString("ForceFeePriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能列表 的本地化字符串。
        /// </summary>
        public static string FunctionList {
            get {
                return ResourceManager.GetString("FunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物信息 的本地化字符串。
        /// </summary>
        public static string GoodsInfo {
            get {
                return ResourceManager.GetString("GoodsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物列表 的本地化字符串。
        /// </summary>
        public static string GoodsList {
            get {
                return ResourceManager.GetString("GoodsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐列表 的本地化字符串。
        /// </summary>
        public static string ReverseList {
            get {
                return ResourceManager.GetString("ReverseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算公式列表 的本地化字符串。
        /// </summary>
        public static string SettlementExpressionList {
            get {
                return ResourceManager.GetString("SettlementExpressionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算价格列表 的本地化字符串。
        /// </summary>
        public static string SettlementPriceList {
            get {
                return ResourceManager.GetString("SettlementPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存列表 的本地化字符串。
        /// </summary>
        public static string StocksList {
            get {
                return ResourceManager.GetString("StocksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓储费价格列表 的本地化字符串。
        /// </summary>
        public static string StorageFeePriceList {
            get {
                return ResourceManager.GetString("StorageFeePriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总产值 的本地化字符串。
        /// </summary>
        public static string TotalOutput {
            get {
                return ResourceManager.GetString("TotalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费计算 的本地化字符串。
        /// </summary>
        public static string TransportChargesCompute {
            get {
                return ResourceManager.GetString("TransportChargesCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费月结 的本地化字符串。
        /// </summary>
        public static string TransportChargesComputeMonthlyStatement {
            get {
                return ResourceManager.GetString("TransportChargesComputeMonthlyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费自提 的本地化字符串。
        /// </summary>
        public static string TransportChargesComputePickUpSelf {
            get {
                return ResourceManager.GetString("TransportChargesComputePickUpSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运价格列表 的本地化字符串。
        /// </summary>
        public static string TransportPriceList {
            get {
                return ResourceManager.GetString("TransportPriceList", resourceCulture);
            }
        }
    }
}
