//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSoft.LS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSoft.LS.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 ShiyeLS Mobile 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加配载计划 的本地化字符串。
        /// </summary>
        public static string AddDispatchedPlan {
            get {
                return ResourceManager.GetString("AddDispatchedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShiyeLS十野物流业务处理系统 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批价格 的本地化字符串。
        /// </summary>
        public static string ApproveContract {
            get {
                return ResourceManager.GetString("ApproveContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批合同价格 的本地化字符串。
        /// </summary>
        public static string ApproveContracts {
            get {
                return ResourceManager.GetString("ApproveContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批发货计划 的本地化字符串。
        /// </summary>
        public static string ApproveDeliverPlans {
            get {
                return ResourceManager.GetString("ApproveDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批意见 的本地化字符串。
        /// </summary>
        public static string ApproveOpinion {
            get {
                return ResourceManager.GetString("ApproveOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配权限 的本地化字符串。
        /// </summary>
        public static string AssignPermissions {
            get {
                return ResourceManager.GetString("AssignPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请问 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物交接承运合同 的本地化字符串。
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户审批意见 的本地化字符串。
        /// </summary>
        public static string CustomerApproveOpinion {
            get {
                return ResourceManager.GetString("CustomerApproveOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户审批纸发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerApprovePaperPlans {
            get {
                return ResourceManager.GetString("CustomerApprovePaperPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户录入纸直发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerNewNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("CustomerNewNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户新增纸发货计划 的本地化字符串。
        /// </summary>
        public static string CustomerNewPaperPlan {
            get {
                return ResourceManager.GetString("CustomerNewPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运费对帐单 的本地化字符串。
        /// </summary>
        public static string CustomerTransportChargesStatement {
            get {
                return ResourceManager.GetString("CustomerTransportChargesStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制表格 的本地化字符串。
        /// </summary>
        public static string CustomGrid {
            get {
                return ResourceManager.GetString("CustomGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤消发货计划 的本地化字符串。
        /// </summary>
        public static string DeleteDeliverPlans {
            get {
                return ResourceManager.GetString("DeleteDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货单 的本地化字符串。
        /// </summary>
        public static string DeliverBill {
            get {
                return ResourceManager.GetString("DeliverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度罐发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchCanPlan {
            get {
                return ResourceManager.GetString("DispatchCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度计划 的本地化字符串。
        /// </summary>
        public static string DispatchDeliverPlans {
            get {
                return ResourceManager.GetString("DispatchDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度历史记录 的本地化字符串。
        /// </summary>
        public static string DispatchHistories {
            get {
                return ResourceManager.GetString("DispatchHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度方便面发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchNoodlePlan {
            get {
                return ResourceManager.GetString("DispatchNoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度罐直发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchNotDeliverCanPlan {
            get {
                return ResourceManager.GetString("DispatchNotDeliverCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度纸直发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("DispatchNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度其它发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchOtherPlan {
            get {
                return ResourceManager.GetString("DispatchOtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度纸发货计划 的本地化字符串。
        /// </summary>
        public static string DispatchPaperPlan {
            get {
                return ResourceManager.GetString("DispatchPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿订单列表 的本地化字符串。
        /// </summary>
        public static string DraftOrders {
            get {
                return ResourceManager.GetString("DraftOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入查询条件 的本地化字符串。
        /// </summary>
        public static string EnterCondition {
            get {
                return ResourceManager.GetString("EnterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入罚款金额 的本地化字符串。
        /// </summary>
        public static string EnterFineAmount {
            get {
                return ResourceManager.GetString("EnterFineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入意见 的本地化字符串。
        /// </summary>
        public static string EnterOpinion {
            get {
                return ResourceManager.GetString("EnterOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇总收发存 的本地化字符串。
        /// </summary>
        public static string EnterOutBalanceSummary {
            get {
                return ResourceManager.GetString("EnterOutBalanceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入回单信息 的本地化字符串。
        /// </summary>
        public static string EnterReceipt {
            get {
                return ResourceManager.GetString("EnterReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入冲帐金额 的本地化字符串。
        /// </summary>
        public static string EnterReverseAmount {
            get {
                return ResourceManager.GetString("EnterReverseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差入库 的本地化字符串。
        /// </summary>
        public static string EnterStockEndDifferences {
            get {
                return ResourceManager.GetString("EnterStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物入库 的本地化字符串。
        /// </summary>
        public static string EnterWarehouse {
            get {
                return ResourceManager.GetString("EnterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错啦 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罚款处理 的本地化字符串。
        /// </summary>
        public static string FineContracts {
            get {
                return ResourceManager.GetString("FineContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物列表 的本地化字符串。
        /// </summary>
        public static string GoodsList {
            get {
                return ResourceManager.GetString("GoodsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入客户 的本地化字符串。
        /// </summary>
        public static string ImportCustomers {
            get {
                return ResourceManager.GetString("ImportCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入货物档案 的本地化字符串。
        /// </summary>
        public static string ImportGoods {
            get {
                return ResourceManager.GetString("ImportGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShiyeLS十野物流业务处理手机系统 的本地化字符串。
        /// </summary>
        public static string MobileAppName {
            get {
                return ResourceManager.GetString("MobileAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改登录帐号 的本地化字符串。
        /// </summary>
        public static string ModifyAccount {
            get {
                return ResourceManager.GetString("ModifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改处理条件 的本地化字符串。
        /// </summary>
        public static string ModifyApproveFlowStepCondition {
            get {
                return ResourceManager.GetString("ModifyApproveFlowStepCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改罐发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyCanPlan {
            get {
                return ResourceManager.GetString("ModifyCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改承运单位档案 的本地化字符串。
        /// </summary>
        public static string ModifyCarrier {
            get {
                return ResourceManager.GetString("ModifyCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改承运单位车辆信息 的本地化字符串。
        /// </summary>
        public static string ModifyCarrierCar {
            get {
                return ResourceManager.GetString("ModifyCarrierCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改承运单位驾驶员信息 的本地化字符串。
        /// </summary>
        public static string ModifyCarrierDriver {
            get {
                return ResourceManager.GetString("ModifyCarrierDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改承运单位结算公式 的本地化字符串。
        /// </summary>
        public static string ModifyCarrierSettlementExpression {
            get {
                return ResourceManager.GetString("ModifyCarrierSettlementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改承运单位运费价格 的本地化字符串。
        /// </summary>
        public static string ModifyCarrierTransportPrice {
            get {
                return ResourceManager.GetString("ModifyCarrierTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string ModifyCity {
            get {
                return ResourceManager.GetString("ModifyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改合同 的本地化字符串。
        /// </summary>
        public static string ModifyContract {
            get {
                return ResourceManager.GetString("ModifyContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改合同发货数据 的本地化字符串。
        /// </summary>
        public static string ModifyContractGoods {
            get {
                return ResourceManager.GetString("ModifyContractGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改国家 的本地化字符串。
        /// </summary>
        public static string ModifyCountry {
            get {
                return ResourceManager.GetString("ModifyCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户档案 的本地化字符串。
        /// </summary>
        public static string ModifyCustomer {
            get {
                return ResourceManager.GetString("ModifyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户力支费价格 的本地化字符串。
        /// </summary>
        public static string ModifyCustomerForceFeePrice {
            get {
                return ResourceManager.GetString("ModifyCustomerForceFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户仓储费价格 的本地化字符串。
        /// </summary>
        public static string ModifyCustomerStorageFeePrice {
            get {
                return ResourceManager.GetString("ModifyCustomerStorageFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户结算价格 的本地化字符串。
        /// </summary>
        public static string ModifyCustomerTransportPrice {
            get {
                return ResourceManager.GetString("ModifyCustomerTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改数据 的本地化字符串。
        /// </summary>
        public static string ModifyData {
            get {
                return ResourceManager.GetString("ModifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改送货单 的本地化字符串。
        /// </summary>
        public static string ModifyDeliverBill {
            get {
                return ResourceManager.GetString("ModifyDeliverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改调度单 的本地化字符串。
        /// </summary>
        public static string ModifyDispatchBill {
            get {
                return ResourceManager.GetString("ModifyDispatchBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改配载计划 的本地化字符串。
        /// </summary>
        public static string ModifyDispatchedPlan {
            get {
                return ResourceManager.GetString("ModifyDispatchedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改入库货物 的本地化字符串。
        /// </summary>
        public static string ModifyEnterWarehouseBillGoods {
            get {
                return ResourceManager.GetString("ModifyEnterWarehouseBillGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改货物档案 的本地化字符串。
        /// </summary>
        public static string ModifyGoods {
            get {
                return ResourceManager.GetString("ModifyGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改货物类别 的本地化字符串。
        /// </summary>
        public static string ModifyGoodsType {
            get {
                return ResourceManager.GetString("ModifyGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改方便面发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyNoodlePlan {
            get {
                return ResourceManager.GetString("ModifyNoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改罐直发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyNotDeliverCanPlan {
            get {
                return ResourceManager.GetString("ModifyNotDeliverCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改纸直发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("ModifyNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改组织部门 的本地化字符串。
        /// </summary>
        public static string ModifyOrganization {
            get {
                return ResourceManager.GetString("ModifyOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改其它发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyOtherPlan {
            get {
                return ResourceManager.GetString("ModifyOtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改纸发货计划 的本地化字符串。
        /// </summary>
        public static string ModifyPaperPlan {
            get {
                return ResourceManager.GetString("ModifyPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改权限组 的本地化字符串。
        /// </summary>
        public static string ModifyPermissionGroup {
            get {
                return ResourceManager.GetString("ModifyPermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改计划审批步骤 的本地化字符串。
        /// </summary>
        public static string ModifyPlanApproveStep {
            get {
                return ResourceManager.GetString("ModifyPlanApproveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改货物信息 的本地化字符串。
        /// </summary>
        public static string ModifyPlanGoods {
            get {
                return ResourceManager.GetString("ModifyPlanGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改岗位 的本地化字符串。
        /// </summary>
        public static string ModifyPosition {
            get {
                return ResourceManager.GetString("ModifyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改价格审批步骤 的本地化字符串。
        /// </summary>
        public static string ModifyPriceApproveStep {
            get {
                return ResourceManager.GetString("ModifyPriceApproveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string ModifyProvince {
            get {
                return ResourceManager.GetString("ModifyProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改收货单位档案 的本地化字符串。
        /// </summary>
        public static string ModifyReceiver {
            get {
                return ResourceManager.GetString("ModifyReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改收货单位距离记录 的本地化字符串。
        /// </summary>
        public static string ModifyReceiverDistance {
            get {
                return ResourceManager.GetString("ModifyReceiverDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改备注 的本地化字符串。
        /// </summary>
        public static string ModifyRemark {
            get {
                return ResourceManager.GetString("ModifyRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改出仓单 的本地化字符串。
        /// </summary>
        public static string ModifyShipmentBill {
            get {
                return ResourceManager.GetString("ModifyShipmentBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改员工档案 的本地化字符串。
        /// </summary>
        public static string ModifyStaff {
            get {
                return ResourceManager.GetString("ModifyStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改运费 的本地化字符串。
        /// </summary>
        public static string ModifyTransportCharges {
            get {
                return ResourceManager.GetString("ModifyTransportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改运费限价记录 的本地化字符串。
        /// </summary>
        public static string ModifyTransportLimitedPrice {
            get {
                return ResourceManager.GetString("ModifyTransportLimitedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改仓库资料 的本地化字符串。
        /// </summary>
        public static string ModifyWarehouse {
            get {
                return ResourceManager.GetString("ModifyWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物移库 的本地化字符串。
        /// </summary>
        public static string MoveWarehouse {
            get {
                return ResourceManager.GetString("MoveWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增登录帐号 的本地化字符串。
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增处理条件 的本地化字符串。
        /// </summary>
        public static string NewApproveFlowStepCondition {
            get {
                return ResourceManager.GetString("NewApproveFlowStepCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增罐发货计划 的本地化字符串。
        /// </summary>
        public static string NewCanPlan {
            get {
                return ResourceManager.GetString("NewCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位档案 的本地化字符串。
        /// </summary>
        public static string NewCarrier {
            get {
                return ResourceManager.GetString("NewCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位车辆信息 的本地化字符串。
        /// </summary>
        public static string NewCarrierCar {
            get {
                return ResourceManager.GetString("NewCarrierCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位驾驶员信息 的本地化字符串。
        /// </summary>
        public static string NewCarrierDriver {
            get {
                return ResourceManager.GetString("NewCarrierDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位结算公式 的本地化字符串。
        /// </summary>
        public static string NewCarrierSettlementExpression {
            get {
                return ResourceManager.GetString("NewCarrierSettlementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位运费结算记录 的本地化字符串。
        /// </summary>
        public static string NewCarrierTransportChargesSettlement {
            get {
                return ResourceManager.GetString("NewCarrierTransportChargesSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增承运单位运费价格 的本地化字符串。
        /// </summary>
        public static string NewCarrierTransportPrice {
            get {
                return ResourceManager.GetString("NewCarrierTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string NewCity {
            get {
                return ResourceManager.GetString("NewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增合同 的本地化字符串。
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增国家 的本地化字符串。
        /// </summary>
        public static string NewCountry {
            get {
                return ResourceManager.GetString("NewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户档案 的本地化字符串。
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户力支费价格 的本地化字符串。
        /// </summary>
        public static string NewCustomerForceFeePrice {
            get {
                return ResourceManager.GetString("NewCustomerForceFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户仓储力支费结算记录 的本地化字符串。
        /// </summary>
        public static string NewCustomerStorageAndForceFeeSettlement {
            get {
                return ResourceManager.GetString("NewCustomerStorageAndForceFeeSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户仓储仓储费结算记录 的本地化字符串。
        /// </summary>
        public static string NewCustomerStorageFeePrice {
            get {
                return ResourceManager.GetString("NewCustomerStorageFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户运费结算记录 的本地化字符串。
        /// </summary>
        public static string NewCustomerTransportChargesSettlement {
            get {
                return ResourceManager.GetString("NewCustomerTransportChargesSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户结算价格 的本地化字符串。
        /// </summary>
        public static string NewCustomerTransportPrice {
            get {
                return ResourceManager.GetString("NewCustomerTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入特殊承运价格 的本地化字符串。
        /// </summary>
        public static string NewDeliverBillCarrierTransportPrice {
            get {
                return ResourceManager.GetString("NewDeliverBillCarrierTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入特殊结算价格 的本地化字符串。
        /// </summary>
        public static string NewDeliverBillCustomerTransportPrice {
            get {
                return ResourceManager.GetString("NewDeliverBillCustomerTransportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增调度单 的本地化字符串。
        /// </summary>
        public static string NewDispatchBill {
            get {
                return ResourceManager.GetString("NewDispatchBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增入库货物 的本地化字符串。
        /// </summary>
        public static string NewEnterWarehouseBillGoods {
            get {
                return ResourceManager.GetString("NewEnterWarehouseBillGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增货物档案 的本地化字符串。
        /// </summary>
        public static string NewGoods {
            get {
                return ResourceManager.GetString("NewGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增货物类别 的本地化字符串。
        /// </summary>
        public static string NewGoodsType {
            get {
                return ResourceManager.GetString("NewGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增方便面发货计划 的本地化字符串。
        /// </summary>
        public static string NewNoodlePlan {
            get {
                return ResourceManager.GetString("NewNoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入罐直发货计划 的本地化字符串。
        /// </summary>
        public static string NewNotDeliverCanPlan {
            get {
                return ResourceManager.GetString("NewNotDeliverCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入纸直发货计划 的本地化字符串。
        /// </summary>
        public static string NewNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("NewNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增组织部门 的本地化字符串。
        /// </summary>
        public static string NewOrganization {
            get {
                return ResourceManager.GetString("NewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增其它发货计划 的本地化字符串。
        /// </summary>
        public static string NewOtherPlan {
            get {
                return ResourceManager.GetString("NewOtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增纸发货计划 的本地化字符串。
        /// </summary>
        public static string NewPaperPlan {
            get {
                return ResourceManager.GetString("NewPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增权限组 的本地化字符串。
        /// </summary>
        public static string NewPermissionGroup {
            get {
                return ResourceManager.GetString("NewPermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增计划审批步骤 的本地化字符串。
        /// </summary>
        public static string NewPlanApproveStep {
            get {
                return ResourceManager.GetString("NewPlanApproveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增货物信息 的本地化字符串。
        /// </summary>
        public static string NewPlanGoods {
            get {
                return ResourceManager.GetString("NewPlanGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增岗位 的本地化字符串。
        /// </summary>
        public static string NewPosition {
            get {
                return ResourceManager.GetString("NewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增价格审批步骤 的本地化字符串。
        /// </summary>
        public static string NewPriceApproveStep {
            get {
                return ResourceManager.GetString("NewPriceApproveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string NewProvince {
            get {
                return ResourceManager.GetString("NewProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增收货单位档案 的本地化字符串。
        /// </summary>
        public static string NewReceiver {
            get {
                return ResourceManager.GetString("NewReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增收货单位距离记录 的本地化字符串。
        /// </summary>
        public static string NewReceiverDistance {
            get {
                return ResourceManager.GetString("NewReceiverDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增员工档案 的本地化字符串。
        /// </summary>
        public static string NewStaff {
            get {
                return ResourceManager.GetString("NewStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增运费限价记录 的本地化字符串。
        /// </summary>
        public static string NewTransportLimitedPrice {
            get {
                return ResourceManager.GetString("NewTransportLimitedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增仓库资料 的本地化字符串。
        /// </summary>
        public static string NewWarehouse {
            get {
                return ResourceManager.GetString("NewWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾差出库 的本地化字符串。
        /// </summary>
        public static string OutStockEndDifferences {
            get {
                return ResourceManager.GetString("OutStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物出库 的本地化字符串。
        /// </summary>
        public static string OutWarehouse {
            get {
                return ResourceManager.GetString("OutWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印划拨出仓单 的本地化字符串。
        /// </summary>
        public static string PrintAllocateShipmentBills {
            get {
                return ResourceManager.GetString("PrintAllocateShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印合同 的本地化字符串。
        /// </summary>
        public static string PrintContract {
            get {
                return ResourceManager.GetString("PrintContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印合同 的本地化字符串。
        /// </summary>
        public static string PrintContracts {
            get {
                return ResourceManager.GetString("PrintContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印送货单 的本地化字符串。
        /// </summary>
        public static string PrintDeliverBill {
            get {
                return ResourceManager.GetString("PrintDeliverBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印送货单 的本地化字符串。
        /// </summary>
        public static string PrintDeliverBills {
            get {
                return ResourceManager.GetString("PrintDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印调度出仓单 的本地化字符串。
        /// </summary>
        public static string PrintDispatchedShipmentBills {
            get {
                return ResourceManager.GetString("PrintDispatchedShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印出仓单 的本地化字符串。
        /// </summary>
        public static string PrintShipmentBill {
            get {
                return ResourceManager.GetString("PrintShipmentBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印盘点表 的本地化字符串。
        /// </summary>
        public static string PrintStocktaking {
            get {
                return ResourceManager.GetString("PrintStocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收送货单回单 的本地化字符串。
        /// </summary>
        public static string ReceiptDeliverBills {
            get {
                return ResourceManager.GetString("ReceiptDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补打送货单 的本地化字符串。
        /// </summary>
        public static string ReprintDeliverBills {
            get {
                return ResourceManager.GetString("ReprintDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补打出仓单 的本地化字符串。
        /// </summary>
        public static string ReprintShipmentBills {
            get {
                return ResourceManager.GetString("ReprintShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化密码 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲帐处理 的本地化字符串。
        /// </summary>
        public static string ReverseContracts {
            get {
                return ResourceManager.GetString("ReverseContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存罚款记录 的本地化字符串。
        /// </summary>
        public static string SaveFines {
            get {
                return ResourceManager.GetString("SaveFines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存冲帐记录 的本地化字符串。
        /// </summary>
        public static string SaveReverses {
            get {
                return ResourceManager.GetString("SaveReverses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询承运单位运费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchCarrierTransportChargesSettlements {
            get {
                return ResourceManager.GetString("SearchCarrierTransportChargesSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询寄库计划 的本地化字符串。
        /// </summary>
        public static string SearchConsigningDeliverPlans {
            get {
                return ResourceManager.GetString("SearchConsigningDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询合同审批信息 的本地化字符串。
        /// </summary>
        public static string SearchContracts {
            get {
                return ResourceManager.GetString("SearchContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询客户运费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchCustomerTransportChargesSettlements {
            get {
                return ResourceManager.GetString("SearchCustomerTransportChargesSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询特殊承运价格记录 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillCarrierTransportPrices {
            get {
                return ResourceManager.GetString("SearchDeliverBillCarrierTransportPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询特殊结算价格记录 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillCustomerTransportPrices {
            get {
                return ResourceManager.GetString("SearchDeliverBillCustomerTransportPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询送货单回单 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBillReceipts {
            get {
                return ResourceManager.GetString("SearchDeliverBillReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询送货单 的本地化字符串。
        /// </summary>
        public static string SearchDeliverBills {
            get {
                return ResourceManager.GetString("SearchDeliverBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询计划 的本地化字符串。
        /// </summary>
        public static string SearchDeliverPlans {
            get {
                return ResourceManager.GetString("SearchDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询入库记录 的本地化字符串。
        /// </summary>
        public static string SearchEnterWarehouseBills {
            get {
                return ResourceManager.GetString("SearchEnterWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询罚款记录 的本地化字符串。
        /// </summary>
        public static string SearchFines {
            get {
                return ResourceManager.GetString("SearchFines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询移库记录 的本地化字符串。
        /// </summary>
        public static string SearchMoveWarehouseBills {
            get {
                return ResourceManager.GetString("SearchMoveWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询出库记录 的本地化字符串。
        /// </summary>
        public static string SearchOutWarehouseBills {
            get {
                return ResourceManager.GetString("SearchOutWarehouseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询冲帐记录 的本地化字符串。
        /// </summary>
        public static string SearchReverses {
            get {
                return ResourceManager.GetString("SearchReverses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询库存尾差 的本地化字符串。
        /// </summary>
        public static string SearchStockEndDifferences {
            get {
                return ResourceManager.GetString("SearchStockEndDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询仓储力支费结算记录 的本地化字符串。
        /// </summary>
        public static string SearchStorageAndForceFeeSettlements {
            get {
                return ResourceManager.GetString("SearchStorageAndForceFeeSettlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择车号 的本地化字符串。
        /// </summary>
        public static string SelectCarNo {
            get {
                return ResourceManager.GetString("SelectCarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择货物 的本地化字符串。
        /// </summary>
        public static string SelectGoods {
            get {
                return ResourceManager.GetString("SelectGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置登录帐号 的本地化字符串。
        /// </summary>
        public static string SetAccount {
            get {
                return ResourceManager.GetString("SetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置承运单位档案 的本地化字符串。
        /// </summary>
        public static string SetCarrier {
            get {
                return ResourceManager.GetString("SetCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置市/县/区/镇 的本地化字符串。
        /// </summary>
        public static string SetCity {
            get {
                return ResourceManager.GetString("SetCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置国家 的本地化字符串。
        /// </summary>
        public static string SetCountry {
            get {
                return ResourceManager.GetString("SetCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置客户 的本地化字符串。
        /// </summary>
        public static string SetCustomer {
            get {
                return ResourceManager.GetString("SetCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置驾驶员档案 的本地化字符串。
        /// </summary>
        public static string SetDriver {
            get {
                return ResourceManager.GetString("SetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置货物档案 的本地化字符串。
        /// </summary>
        public static string SetGoods {
            get {
                return ResourceManager.GetString("SetGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置货物类别 的本地化字符串。
        /// </summary>
        public static string SetGoodsType {
            get {
                return ResourceManager.GetString("SetGoodsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置组织结构 的本地化字符串。
        /// </summary>
        public static string SetOrganization {
            get {
                return ResourceManager.GetString("SetOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置权限组 的本地化字符串。
        /// </summary>
        public static string SetPermissionGroup {
            get {
                return ResourceManager.GetString("SetPermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置计划审批流程 的本地化字符串。
        /// </summary>
        public static string SetPlanApproveFlow {
            get {
                return ResourceManager.GetString("SetPlanApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置岗位 的本地化字符串。
        /// </summary>
        public static string SetPosition {
            get {
                return ResourceManager.GetString("SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置价格审批流程 的本地化字符串。
        /// </summary>
        public static string SetPriceApproveFlow {
            get {
                return ResourceManager.GetString("SetPriceApproveFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置省/州/自治区/直辖市 的本地化字符串。
        /// </summary>
        public static string SetProvince {
            get {
                return ResourceManager.GetString("SetProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置收货单位档案 的本地化字符串。
        /// </summary>
        public static string SetReceiver {
            get {
                return ResourceManager.GetString("SetReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置员工 的本地化字符串。
        /// </summary>
        public static string SetStaff {
            get {
                return ResourceManager.GetString("SetStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置运费限价记录 的本地化字符串。
        /// </summary>
        public static string SetTransportLimitedPrice {
            get {
                return ResourceManager.GetString("SetTransportLimitedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置仓库资料 的本地化字符串。
        /// </summary>
        public static string SetWarehouse {
            get {
                return ResourceManager.GetString("SetWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出仓单 的本地化字符串。
        /// </summary>
        public static string ShipmentBill {
            get {
                return ResourceManager.GetString("ShipmentBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起 的本地化字符串。
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承运单位对帐 的本地化字符串。
        /// </summary>
        public static string StatCarrierStatement {
            get {
                return ResourceManager.GetString("StatCarrierStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户对帐 的本地化字符串。
        /// </summary>
        public static string StatCustomerStatement {
            get {
                return ResourceManager.GetString("StatCustomerStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计客户总产值 的本地化字符串。
        /// </summary>
        public static string StatCustomerTotalOutput {
            get {
                return ResourceManager.GetString("StatCustomerTotalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计办事处毛利率 的本地化字符串。
        /// </summary>
        public static string StatOrganGrossProfitRate {
            get {
                return ResourceManager.GetString("StatOrganGrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计办事处总产值 的本地化字符串。
        /// </summary>
        public static string StatOrganTotalOutput {
            get {
                return ResourceManager.GetString("StatOrganTotalOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计仓储力支费 的本地化字符串。
        /// </summary>
        public static string StatStorageAndForceFee {
            get {
                return ResourceManager.GetString("StatStorageAndForceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表 的本地化字符串。
        /// </summary>
        public static string Stocktaking {
            get {
                return ResourceManager.GetString("Stocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交罐发货计划 的本地化字符串。
        /// </summary>
        public static string SubmitCanPlan {
            get {
                return ResourceManager.GetString("SubmitCanPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交合同 的本地化字符串。
        /// </summary>
        public static string SubmitContract {
            get {
                return ResourceManager.GetString("SubmitContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交合同 的本地化字符串。
        /// </summary>
        public static string SubmitContracts {
            get {
                return ResourceManager.GetString("SubmitContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交计划 的本地化字符串。
        /// </summary>
        public static string SubmitDeliverPlans {
            get {
                return ResourceManager.GetString("SubmitDeliverPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交调度单 的本地化字符串。
        /// </summary>
        public static string SubmitDispatchBill {
            get {
                return ResourceManager.GetString("SubmitDispatchBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交调度单 的本地化字符串。
        /// </summary>
        public static string SubmitDispatchBills {
            get {
                return ResourceManager.GetString("SubmitDispatchBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交方便面发货计划 的本地化字符串。
        /// </summary>
        public static string SubmitNoodlePlan {
            get {
                return ResourceManager.GetString("SubmitNoodlePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交纸直发货计划 的本地化字符串。
        /// </summary>
        public static string SubmitNotDeliverPaperPlan {
            get {
                return ResourceManager.GetString("SubmitNotDeliverPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交其它发货计划 的本地化字符串。
        /// </summary>
        public static string SubmitOtherPlan {
            get {
                return ResourceManager.GetString("SubmitOtherPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交纸发货计划 的本地化字符串。
        /// </summary>
        public static string SubmitPaperPlan {
            get {
                return ResourceManager.GetString("SubmitPaperPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交出仓单 的本地化字符串。
        /// </summary>
        public static string SubmitShipmentBills {
            get {
                return ResourceManager.GetString("SubmitShipmentBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综合查询 的本地化字符串。
        /// </summary>
        public static string SyntheticalSearch {
            get {
                return ResourceManager.GetString("SyntheticalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看罐发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewCanPlanDetails {
            get {
                return ResourceManager.GetString("ViewCanPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看待调度罐发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewDispatchCanPlanDetails {
            get {
                return ResourceManager.GetString("ViewDispatchCanPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看待调度方便面发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewDispatchNoodlePlanDetails {
            get {
                return ResourceManager.GetString("ViewDispatchNoodlePlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看待调度其它发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewDispatchOtherPlanDetails {
            get {
                return ResourceManager.GetString("ViewDispatchOtherPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看待调度纸发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewDispatchPaperPlanDetails {
            get {
                return ResourceManager.GetString("ViewDispatchPaperPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看方便面发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewNoodlePlanDetails {
            get {
                return ResourceManager.GetString("ViewNoodlePlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看其它发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewOtherPlanDetails {
            get {
                return ResourceManager.GetString("ViewOtherPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看纸发货计划详细信息 的本地化字符串。
        /// </summary>
        public static string ViewPaperPlanDetails {
            get {
                return ResourceManager.GetString("ViewPaperPlanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看员工详细信息 的本地化字符串。
        /// </summary>
        public static string ViewStaffDetails {
            get {
                return ResourceManager.GetString("ViewStaffDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎登录 的本地化字符串。
        /// </summary>
        public static string WelcomeLogin {
            get {
                return ResourceManager.GetString("WelcomeLogin", resourceCulture);
            }
        }
    }
}
